In [1]:
import numpy as np


In [2]:
# 生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列
arr= np.arange(21)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# 將以上數列取出偶數
arr2=arr[0:21:2]
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [4]:
# 將數列取出 3 的倍數
arr3=arr[0:21:3]
print(arr3)

[ 0  3  6  9 12 15 18]
