# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [10]:
array = np.arange(1,12)
ans = []
for i in array:
    if i>2 and i<7:
        ans.append(-i)
    else :
        ans.append(i)

print(ans)

[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [11]:
A = np.random.rand(3, 6)

count = A > 0.5 

print(count.sum())


[[0.06132886 0.87250224 0.77282982 0.5450019  0.47711249 0.40798953]
 [0.76610161 0.51807546 0.01516464 0.30938675 0.13064512 0.59448389]
 [0.08606754 0.22025999 0.99664118 0.39498382 0.1179233  0.51581842]]
[[False  True  True  True False False]
 [ True  True False False False  True]
 [False False  True False False  True]]
8


'\nYour Code\n'